### ISSUE TITLE
about yaml file

### ISSUE THREAD

**Issue by ydlu** [RLGC-Project/RLGC#4]
when I try to create virtual environemnt from the yaml file you privided, I encounter error like ResolvePackagesNotFound. I guess the YAML includes platform-specific build constraints, so it fails when I'm transferring across platform.

**Comment by ydlu** [comment]
I suggest you use the command below when you export your env setting.`conda env export -n py36 -f py36.yml --no-builds`

**Comment by ydlu** [comment]
Besides, when I run the `python trainIEEE39LoadSheddingAgent_continuous_action_DDPG.py ` or  `python trainIEEE39LoadSheddingAgent_discrete_action.py`, I run into the same error like following, 

`py4j.protocol.Py4JJavaError: An error occurred while calling t.initStudyCase.
: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.ieee.odm.adapter.psse.impl.PSSEDynAdapter.parseInputFile(PSSEDynAdapter.java:136)
	at org.ieee.odm.adapter.psse.PSSEAdapter.parseDstabFiles(PSSEAdapter.java:101)
	at org.ieee.odm.adapter.psse.PSSEAdapter.parseInputFile(PSSEAdapter.java:116)
	at org.ieee.odm.adapter.AbstractODMAdapter.parseInputFile(AbstractODMAdapter.java:234)
	at org.ieee.odm.adapter.AbstractODMAdapter.parseInputStream(AbstractODMAdapter.java:191)
	at org.ieee.odm.adapter.AbstractODMAdapter.parseInputFile(AbstractODMAdapter.java:215)
	at org.ieee.odm.adapter.AbstractODMAdapter.parseInputFile(AbstractODMAdapter.java:202)
	at org.pnnl.gov.pss_gateway.IpssPyGateway.loadStudyCase(IpssPyGateway.java:660)
	at org.pnnl.gov.pss_gateway.IpssPyGateway.initStudyCase(IpssPyGateway.java:170)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 20 more
`
I'm not very familiar with py4j and hope to get some guide form you. Thanks 。

**Comment by thuang** [comment]
Could you try the latest version and follow the latest guideline (I have updated the readme.md) ?

**Comment by roki1031** [comment]
> I suggest you use the command below when you export your env setting.`conda env export -n py36 -f py36.yml --no-builds`

still**"ResolvePackagesNotFound."**
